version: '3.7'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 9378:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: labinf
      ME_CONFIG_BASICAUTH_PASSWORD: labinf
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: labinf
    depends_on:
      - mongo
    networks:
      - integration

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: labinf
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - integration

  mysql:
    container_name: mysql
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - integration
    restart: always

  sql-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=as2Group
    ports:
      - "1433:1433"
    volumes:
      - as2-sql-server:/var/opt/mssql
    networks:
      - integration

volumes:
  mongo-data:
  as2-sql-server:
  db-data:

networks:
  integration:
    name: integration
    driver: bridge
    external:
      name: integration
